# Generated by Django 5.1.6 on 2025-02-27 14:36

from django.db import migrations, models

import bookworm.catalog.validations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_category_books_book_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True,
                upload_to="covers/",
                validators=[bookworm.catalog.validations.validate_cover_image],
            ),
        ),
    ]
